services:
  dns:
    build: 
      context: ./dns
      dockerfile: Dockerfile
    container_name: bind9
    ports:
      - "53:53/udp"
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    ports:
      - 80:80